esphome:
  name: sonoff
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"

logger:

api:

ota:

sensor:
  - platform: wifi_signal
    name: sonoff_wifi
    update_interval: 60s
    
  - platform: uptime
    name: sonoff_uptime

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Button"
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Relay"
    pin: GPIO12
    id: relay
    on_turn_on:
      then:
        - output.turn_on: basic_green_led
    on_turn_off:
      then:
        - output.turn_off: basic_green_led

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True
